SYSTEM_ROLES = (
    "platform_super_admin",
    "platform_support",
    "platform_billing",
    "school_admin",
    "school_finance",
    "teacher",
    "bus_attendant",
    "parent",
)

PERMISSIONS: dict[str, str] = {
    "tenant:read": "Read tenant profile",
    "tenant:write": "Update tenant/school profile",
    "staff:read": "Read staff profiles",
    "staff:write": "Write staff profiles",
    "audit:read": "Read audit logs",
    "membership:read": "Read memberships",
    "membership:write": "Write memberships",
    "people:read": "Read school people via admin portal",
    "people:write": "Manage school people via admin portal",
    "operations:read": "Read school operations via admin portal",
    "operations:write": "Manage school operations via admin portal",
    "imports:read": "Read bulk import status and templates",
    "imports:write": "Validate and apply bulk CSV imports",
    "students:read": "Read students",
    "students:create": "Create students",
    "students:update": "Update students",
    "students:withdraw": "Withdraw students",
    "students:hide": "Hide student PII from operational views",
    "students:anonymize": "Anonymize student PII",
    "guardians:read": "Read guardians",
    "guardians:create": "Create guardians",
    "guardians:update": "Update guardians",
    "student_guardians:read": "Read student-guardian links",
    "student_guardians:write": "Manage student-guardian links",
    "enrollments:read": "Read enrollments",
    "enrollments:create": "Create enrollments",
    "enrollments:update": "Update enrollments",
    "academic:read": "Read classes, sections, and academic years",
    "academic:write": "Manage classes, sections, and academic years",
    "files:read": "Read file metadata",
    "files:write": "Create file metadata records",
    "cards:read": "Read physical cards",
    "cards:create": "Register physical cards",
    "cards:update": "Update card metadata",
    "cards:block": "Block physical cards",
    "cards:retire": "Retire physical cards",
    "card_assignments:read": "Read card assignments",
    "card_assignments:create": "Create card assignments",
    "card_assignments:activate": "Activate card assignments",
    "card_assignments:block": "Block card assignments",
    "card_assignments:lost": "Mark card assignments lost",
    "card_assignments:revoke": "Revoke card assignments",
    "card_assignments:replace": "Replace student cards",
    "rfid_readers:create": "Create RFID readers",
    "rfid_readers:read": "Read RFID readers",
    "rfid_readers:update": "Update RFID readers",
    "rfid_devices:create": "Register RFID devices",
    "rfid_devices:read": "Read RFID devices",
    "rfid_devices:update": "Update RFID devices",
    "rfid_devices:rotate_keys": "Rotate RFID device keys",
    "rfid_events:read": "Read RFID events",
    "attendance:read": "Read attendance records",
    "attendance:create": "Create attendance records",
    "attendance:update": "Update attendance records",
    "attendance:correct": "Correct attendance records",
    "attendance:finalize": "Finalize daily attendance",
    "attendance:manage_policy": "Manage attendance policies",
    "buses:read": "Read buses",
    "buses:create": "Create buses",
    "buses:update": "Update buses",
    "routes:read": "Read transport routes",
    "routes:create": "Create transport routes",
    "routes:update": "Update transport routes",
    "route_stops:read": "Read route stops",
    "route_stops:write": "Manage route stops",
    "transport_assignments:read": "Read student transport assignments",
    "transport_assignments:write": "Manage student transport assignments",
    "transport_attendants:read": "Read transport attendants",
    "transport_attendants:write": "Manage transport attendants",
    "trips:read": "Read transport trips",
    "trips:write": "Manage transport trips",
    "transport_nfc:sync": "Submit transport NFC client events",
    "transport_boarding:read": "Read transport boarding records",
    "gps_samples:sync": "Submit transport GPS location samples",
    "gps_samples:read": "Read transport GPS location history",
    "parent:gps_read": "Read current bus location for linked children",
    "parent:push_register": "Register mobile device for push notifications",
    "parent:children_read": "List children linked to the authenticated parent",
    "parent:attendance_read": "Read attendance for linked children",
    "parent:notifications_read": "Read parent notification inbox",
    "parent:notifications_preferences": "Manage parent notification preferences",
    "teacher:me_read": "Read authenticated teacher profile",
    "teacher:classes_read": "List teacher class assignments",
    "teacher:students_read": "List students in assigned classes",
    "teacher:attendance_read": "Read attendance for assigned classes",
    "teacher:attendance_write": "Mark or correct attendance for assigned classes",
    "teacher:nfc_attendance": "Submit class NFC attendance events",
    "teacher:timetable_read": "Read teacher timetable",
    "teacher:timetable_write": "Update teacher timetable where authorized",
    "teacher:results_read": "Read results for assigned classes",
    "teacher:results_write": "Enter or update results for assigned classes",
    "teacher:messages_write": "Send messages to parents of authorized students",
    "teacher:notifications_read": "Read teacher notification inbox",
}

ROLE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "platform_super_admin": tuple(PERMISSIONS.keys()),
    "platform_support": (
        "tenant:read",
        "staff:read",
        "audit:read",
        "membership:read",
        "students:read",
        "guardians:read",
        "enrollments:read",
        "people:read",
        "operations:read",
        "academic:read",
        "cards:read",
        "card_assignments:read",
        "rfid_readers:read",
        "rfid_devices:read",
        "rfid_events:read",
        "attendance:read",
    ),
    "platform_billing": ("tenant:read",),
    "school_admin": (
        "tenant:read",
        "tenant:write",
        "staff:read",
        "staff:write",
        "audit:read",
        "membership:read",
        "membership:write",
        "students:read",
        "students:create",
        "students:update",
        "students:withdraw",
        "students:hide",
        "students:anonymize",
        "guardians:read",
        "guardians:create",
        "guardians:update",
        "student_guardians:read",
        "student_guardians:write",
        "enrollments:read",
        "enrollments:create",
        "enrollments:update",
        "people:read",
        "people:write",
        "operations:read",
        "operations:write",
        "imports:read",
        "imports:write",
        "academic:read",
        "academic:write",
        "files:read",
        "files:write",
        "cards:read",
        "cards:create",
        "cards:update",
        "cards:block",
        "cards:retire",
        "card_assignments:read",
        "card_assignments:create",
        "card_assignments:activate",
        "card_assignments:block",
        "card_assignments:lost",
        "card_assignments:revoke",
        "card_assignments:replace",
        "rfid_readers:create",
        "rfid_readers:read",
        "rfid_readers:update",
        "rfid_devices:create",
        "rfid_devices:read",
        "rfid_devices:update",
        "rfid_devices:rotate_keys",
        "rfid_events:read",
        "attendance:read",
        "attendance:create",
        "attendance:update",
        "attendance:correct",
        "attendance:finalize",
        "attendance:manage_policy",
        "buses:read",
        "buses:create",
        "buses:update",
        "routes:read",
        "routes:create",
        "routes:update",
        "route_stops:read",
        "route_stops:write",
        "transport_assignments:read",
        "transport_assignments:write",
        "transport_attendants:read",
        "transport_attendants:write",
        "trips:read",
        "trips:write",
        "transport_nfc:sync",
        "transport_boarding:read",
        "gps_samples:sync",
        "gps_samples:read",
    ),
    "school_finance": (
        "tenant:read",
        "membership:read",
        "students:read",
        "guardians:read",
        "enrollments:read",
        "academic:read",
        "cards:read",
        "card_assignments:read",
        "rfid_readers:read",
        "rfid_devices:read",
        "rfid_events:read",
        "attendance:read",
    ),
    "teacher": (
        "tenant:read",
        "staff:read",
        "students:read",
        "enrollments:read",
        "people:read",
        "academic:read",
        "cards:read",
        "card_assignments:read",
        "rfid_readers:read",
        "rfid_events:read",
        "attendance:read",
        "teacher:me_read",
        "teacher:classes_read",
        "teacher:students_read",
        "teacher:attendance_read",
        "teacher:attendance_write",
        "teacher:nfc_attendance",
        "teacher:timetable_read",
        "teacher:timetable_write",
        "teacher:results_read",
        "teacher:results_write",
        "teacher:messages_write",
        "teacher:notifications_read",
    ),
    "bus_attendant": (
        "tenant:read",
        "students:read",
        "cards:read",
        "card_assignments:read",
        "routes:read",
        "route_stops:read",
        "transport_assignments:read",
        "trips:read",
        "trips:write",
        "transport_nfc:sync",
        "transport_boarding:read",
        "gps_samples:sync",
    ),
    "parent": (
        "tenant:read",
        "students:read",
        "guardians:read",
        "enrollments:read",
        "parent:gps_read",
        "parent:push_register",
        "parent:children_read",
        "parent:attendance_read",
        "parent:notifications_read",
        "parent:notifications_preferences",
    ),
}

PLATFORM_ROLES = {"platform_super_admin", "platform_support", "platform_billing"}
MFA_REQUIRED_ROLES = {"platform_super_admin", "platform_support", "platform_billing", "school_admin"}
