SYSTEM_ROLES = (
    "platform_super_admin",
    "platform_support",
    "platform_billing",
    "school_admin",
    "school_finance",
    "teacher",
    "bus_attendant",
    "parent",
)

PERMISSIONS: dict[str, str] = {
    "tenant:read": "Read tenant profile",
    "staff:read": "Read staff profiles",
    "staff:write": "Write staff profiles",
    "audit:read": "Read audit logs",
    "membership:read": "Read memberships",
    "membership:write": "Write memberships",
    "students:read": "Read students",
    "students:create": "Create students",
    "students:update": "Update students",
    "students:withdraw": "Withdraw students",
    "students:hide": "Hide student PII from operational views",
    "students:anonymize": "Anonymize student PII",
    "guardians:read": "Read guardians",
    "guardians:create": "Create guardians",
    "guardians:update": "Update guardians",
    "student_guardians:read": "Read student-guardian links",
    "student_guardians:write": "Manage student-guardian links",
    "enrollments:read": "Read enrollments",
    "enrollments:create": "Create enrollments",
    "enrollments:update": "Update enrollments",
    "academic:read": "Read classes, sections, and academic years",
    "academic:write": "Manage classes, sections, and academic years",
    "files:read": "Read file metadata",
    "files:write": "Create file metadata records",
}

ROLE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "platform_super_admin": tuple(PERMISSIONS.keys()),
    "platform_support": (
        "tenant:read",
        "staff:read",
        "audit:read",
        "membership:read",
        "students:read",
        "guardians:read",
        "enrollments:read",
        "academic:read",
    ),
    "platform_billing": ("tenant:read",),
    "school_admin": (
        "tenant:read",
        "staff:read",
        "staff:write",
        "audit:read",
        "membership:read",
        "membership:write",
        "students:read",
        "students:create",
        "students:update",
        "students:withdraw",
        "students:hide",
        "students:anonymize",
        "guardians:read",
        "guardians:create",
        "guardians:update",
        "student_guardians:read",
        "student_guardians:write",
        "enrollments:read",
        "enrollments:create",
        "enrollments:update",
        "academic:read",
        "academic:write",
        "files:read",
        "files:write",
    ),
    "school_finance": (
        "tenant:read",
        "membership:read",
        "students:read",
        "guardians:read",
        "enrollments:read",
        "academic:read",
    ),
    "teacher": ("tenant:read", "staff:read", "students:read", "enrollments:read", "academic:read"),
    "bus_attendant": ("tenant:read", "students:read"),
    "parent": ("tenant:read", "students:read", "guardians:read", "enrollments:read"),
}

PLATFORM_ROLES = {"platform_super_admin", "platform_support", "platform_billing"}
MFA_REQUIRED_ROLES = {"platform_super_admin", "platform_support", "platform_billing", "school_admin"}
