"""Notification type and outbox topic constants."""

from __future__ import annotations

NOTIFICATION_TOPIC_DISPATCH = "notification.dispatch"

NOTIFICATION_TYPE_SCHOOL_ENTRY = "school_entry"
NOTIFICATION_TYPE_SCHOOL_EXIT = "school_exit"
NOTIFICATION_TYPE_BUS_BOARDING = "bus_boarding"
NOTIFICATION_TYPE_BUS_DROPOFF = "bus_dropoff"
NOTIFICATION_TYPE_TEACHER_MESSAGE = "teacher_message"

OPERATIONAL_NOTIFICATION_TYPES = frozenset(
    {
        NOTIFICATION_TYPE_SCHOOL_ENTRY,
        NOTIFICATION_TYPE_SCHOOL_EXIT,
        NOTIFICATION_TYPE_BUS_BOARDING,
        NOTIFICATION_TYPE_BUS_DROPOFF,
    }
)

DELIVERY_STATUS_PENDING = "pending"
DELIVERY_STATUS_QUEUED = "queued"
DELIVERY_STATUS_SENT = "sent"
DELIVERY_STATUS_FAILED = "failed"
DELIVERY_STATUS_SKIPPED_PREFERENCE = "skipped_preference"
DELIVERY_STATUS_SKIPPED_NO_DEVICE = "skipped_no_device"

NOTIFICATION_SCHEMA_VERSION = 1
OUTBOX_DISPATCH_SCHEMA_VERSION = 1
